version: "3.9" # Updated to a more recent version

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - mongo
    networks:
      - flight_network

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5433:5432" # Ensure this port is free on your host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flight_network

  mongo:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - flight_network

networks:
  flight_network:

volumes:
  postgres_data:
  mongo_data:
